(fix: 429) Add exponential backoff optional functionality in fetchAndRetry
RequestNetwork/requestNetwork pull request #1077
Opened 2023-02-27 21:54 UTC by mliu

Closes #1076 
Closes [dw-99](https://app.dework.xyz/request-network/development-56861?taskId=e0b018b6-f29a-4e7e-a87e-030c790e792a)

This PR introduces an `exponentialBackoff` optional flag to `fetchAndRetry` calls that increases the time between retried http requests at an exponential rate. These rates are further configurable by setting parameters in `retry.ts` but defaults to an exponential growth rate of 2 and a max cap of 30 seconds (i.e. 2, 4, 8, 16, 30). Existing logic like base delay between retries and maximum retries allowed are still preserved.

2023-02-27 22:05 UTC, MantisClone commented
I should have mentioned this: DeWork recognizes branches like `dw-99/fix-the-thing` but ignores branches like `dw-99-fix-the-thing`  I'm not sure why.  

I don't want you to change the branch name because that would auto-close the PR.  Instead, could you please click the "Submit Work" button on the DeWork task and post the PR link there?

2023-02-27 22:33 UTC, MantisClone requested changes
The request-node supports command-line arguments.  Can you please ensure that passing them as command-line args works and add descriptions to the README?

2023-03-23 21:27 UTC, mliu commented
> The request-node supports command-line arguments. Can you please ensure that passing them as command-line args works and add descriptions to the README?

Discussed offline, the command-line args don't apply here since this is request client executed code. This implementation is already following precedence of previous config values.

2023-03-24 01:39 UTC, MantisClone commented
@mliu I implemented the exponential backoff configuration parameters but wasn't able to push them to your fork so I pushed them to an upstream branch instead: https://github.com/RequestNetwork/requestNetwork/compare/master...dw-99-exponential-backoffs-in-retry

I think this feature may warrant a new test or two in https://github.com/RequestNetwork/requestNetwork/blob/dw-99-exponential-backoffs-in-retry/packages/utils/test/retry.test.ts

2023-03-24 18:25 UTC, mliu commented
Thanks! Added tests

2023-03-28 00:10 UTC, MantisClone approved these changes

2023-03-28 00:46 UTC, MantisClone commented on packages/utils/test/retry.test.ts
> +    // Exponential backoff should only call a second time after 2000ms
This makes me realize that if you want to have back off like: 1 second, 2 seconds, 4 seconds, 8 seconds, then you need to set the `exponentialBackoffDelay` to 500 ms.

2023-03-28 19:37 UTC, merged