feat: base-deployment
RequestNetwork/requestNetwork pull request #1357
Opened 2024-02-20 21:38 UTC by skiv71

## Description of the changes

2024-02-21 08:54 UTC, benjlevesque requested changes
this doesn't look like a standard deployment, addresses don't match other networks

am I missing some contact?

2024-02-21 08:54 UTC, benjlevesque commented on packages/smart-contracts/hardhat.config.ts
> +//'0xE99Ab70a5FAE59551544FA326fA048f7B95A24B2';
why this change?

2024-02-21 09:19 UTC, alexandre-abrioux reviewed
Same comment as @benjlevesque, it looks like this contract was not deployed from RN deployer's contract. It's maybe not a big deal, but it would be better to use RN deployer to:
- have the same contract address on all chains
- approve the deployment through the multi-sig, increasing general trust in the contract, appreciated during security audits

2024-02-21 14:14 UTC, alexandre-abrioux approved these changes

2024-02-22 09:03 UTC, benjlevesque approved these changes

2024-02-22 09:26 UTC, leoslr approved these changes

2024-02-22 12:42 UTC, merged