feat: payment network any to erc20 in advanced logic
RequestNetwork/requestNetwork pull request #414
Opened 2021-02-18 17:19 UTC by vrolland

## Description of the changes

add tthe payment network any to erc20 to the advanced logic

2021-02-18 19:01 UTC, benjlevesque reviewed
any reason you reuse the `IFee...` interfaces? 
it seems to me that this new PN should have its own interfaces, that extend `IFee...`

Otherwise, it would feel like the fee proxy PN accepts those extra parameters

2021-02-19 11:12 UTC, vrolland commented on packages/advanced-logic/src/advanced-logic.ts
> +    anyToErc20Proxy,
Because the package advancedLogic is injected, we need a way to get the specific functions of all the extensions supported by this package.

2021-02-19 12:46 UTC, vrolland commented on packages/advanced-logic/src/advanced-logic.ts
> +    switch (id) {
Done!

2021-02-19 12:49 UTC, vrolland commented on packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts
> +  }
Added to Jira

2021-02-19 12:49 UTC, vrolland commented on packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts
> +    },
Added to Jira

2021-02-19 18:06 UTC, benjlevesque commented on packages/types/src/payment-types.ts
> +  tokensAccepted?: string[];
you created the new interface but forgot to remove the fields from here?

2021-02-19 18:07 UTC, benjlevesque commented on packages/types/src/payment-types.ts
> +  tokenAddress?: string;
shouldn't this also be in a new type?

2021-02-19 18:08 UTC, benjlevesque approved these changes

2021-02-24 14:31 UTC, yomarion requested changes
Getting there, awesome !
Please clean a few things before pushing.

2021-02-24 14:31 UTC, yomarion commented on packages/types/src/payment-types.ts
> +/** Parameters to create a request with "any to erc20" payment network */
```suggestion
/** Parameters to create a request with "fees in reference based" payment network */
```

2021-02-24 14:31 UTC, yomarion commented on packages/types/src/payment-types.ts
> +/** Parameters to create a request with fees in reference based payment network */
```suggestion
/** Parameters to create a request with "any to erc20" payment network */
```

2021-02-25 08:33 UTC, vrolland commented on packages/advanced-logic/src/extensions/payment-network/any-to-erc20-proxy.ts
> + *   `Math.floor(Math.random() * Math.pow(2, 4 * 8)).toString(16) + Math.floor(Math.random() * Math.pow(2, 4 * 8)).toString(16)`
I will have look at this for the refacto

2021-02-25 09:59 UTC, GrandGarcon approved these changes
good PR to review coz it gave needed insights to  the addition of new stadard types ( whether tokens or blockchains ). thanks

2021-02-25 10:27 UTC, benjlevesque approved these changes

2021-02-25 10:32 UTC, AdamDowson approved these changes

2021-02-25 10:32 UTC, yomarion approved these changes
Great work

2021-02-25 10:33 UTC, merged