fix: near address validation
RequestNetwork/requestNetwork pull request #835
Opened 2022-04-22 08:00 UTC by leoslr

Validate address for both of these format:
- `account.near` 
- 32 bytes address

Previously it only validated the `account.near` format

2022-04-22 08:07 UTC, KolevDarko approved these changes

2022-04-26 08:14 UTC, bertux approved these changes
good fix

2022-04-26 14:03 UTC, alexandre-abrioux requested changes
The regex should not be changed IMO as this is the regex found in the specs.
I think you want to change the switch...case and make the prefixes  (`.near `or `.testnet`) optional, like so:
```ts
switch (network) {
    case 'aurora':
      return !!address.match(/[^.]+(\.near)?$/);
    case 'aurora-testnet':
      return !!address.match(/[^.]+(\.testnet)?$/);
    default:
      throw new Error(`Cannot validate NEAR address for network ${network}`);
  }
```
Add tests for this to be sure 😊

2022-04-28 16:20 UTC, alexandre-abrioux approved these changes
👌

2022-04-28 16:45 UTC, merged