Feat: add goerli for storage
RequestNetwork/requestNetwork pull request #889
Opened 2022-07-27 14:08 UTC by rom1trt

## Description of the changes
Merged from master due to unsigned commits on `feat/add-goerli-storage` branch that could not be merged

2022-07-27 14:17 UTC, benjlevesque requested changes
nice. mind the test, it's not the right one

2022-07-27 14:17 UTC, benjlevesque commented on packages/payment-detection/test/erc20/thegraph-info-retriever.test.ts
> +  describe('on goerli', () => {
this test is not about storage, but payment-detection

2022-07-27 14:32 UTC, benjlevesque approved these changes

2022-07-27 15:14 UTC, alexandre-abrioux approved these changes

2022-07-28 08:51 UTC, alexandre-abrioux commented
duplicate of https://github.com/RequestNetwork/requestNetwork/pull/890

2022-07-28 08:51 UTC, closed without merging